version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/bindings/Datadog.Maui"
      - "/bindings/Datadog.Android.Binding"
      - "/bindings/Datadog.Android.Core"
      - "/bindings/Datadog.Android.Internal"
      - "/bindings/Datadog.Android.Logs"
      - "/bindings/Datadog.Android.Rum"
      - "/bindings/Datadog.Android.SessionReplay"
      - "/bindings/Datadog.Android.Trace"
      - "/example"
      - "/tests/Datadog.Maui.Tests"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Datadog.*"

