stages:
  - test

default:
  tags:
    - macos:sequoia-arm64
    - specific:true

test:lint:
  stage: test
  script:
    - dotnet format example.slnx --verify-no-changes --no-restore --severity error

test:build:
  stage: test
  script:
    - ./build.sh

test:unit:
  stage: test
  script:
    - mkdir -p local-packages
    - dotnet test tests/DatadogSdk.Maui.Tests/ --logger "junit;LogFilePath=results.xml"
  artifacts:
    when: always
    reports:
      junit: tests/DatadogSdk.Maui.Tests/results.xml
