<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.Core.cs" />
    <ObjcBindingApiDefinition Include="ApiDefinition.Logs.cs" />
    <ObjcBindingApiDefinition Include="ApiDefinition.Trace.cs" />
    <ObjcBindingApiDefinition Include="ApiDefinition.Rum.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
  </ItemGroup>

  <ItemGroup>
    <NativeReference Include="NativeReference\DatadogWrapper.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
      <SmartLink>True</SmartLink>
    </NativeReference>
  </ItemGroup>
</Project>
