/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2026-Present Datadog, Inc.
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text.Json;
using Microsoft.Maui.Storage;

namespace Datadog.Maui
{
    /// <summary>
    /// Resolves an assembly's PE debug-directory id (CodeView GUID + debug-directory Stamp) —
    /// the same identifier upload-time tooling reads off the compiled DLL/PDB pair — by looking
    /// it up in the build-time debug-id manifest (<c>dd_debug_ids.json</c>, generated by
    /// Datadog.Maui.DebugId.targets, see RUM-18332) that ships as an app asset.
    /// This is intentionally NOT Module.ModuleVersionId (the MVID): the MVID identifies the
    /// managed metadata, not the PE/PDB pairing, and doesn't match what build-time tooling uses
    /// to correlate a binary with its PDB.
    ///
    /// A previous version of this class read the id directly off Assembly.Location via
    /// PEReader at runtime. That only works when the assembly still exists as a loose file on
    /// disk, which is not the case for single-file/AOT-bundled assemblies on packaged
    /// Android/iOS builds — Assembly.Location is empty there, so the old approach silently
    /// returned null for every frame on a real device. The manifest computes the same id at
    /// build time, while the assemblies still exist as real files, so it works regardless of
    /// how assemblies are packaged at runtime.
    /// </summary>
    internal static class AssemblyDebugId
    {
        private const string ManifestFileName = "dd_debug_ids.json";

        private static readonly Lazy<IReadOnlyDictionary<string, string>> _manifest =
            new(LoadManifest, isThreadSafe: true);

        private static IReadOnlyDictionary<string, string>? _manifestOverrideForTests;

        /// <summary>
        /// Returns "{guid:N}{stamp:x8}" for this assembly's simple name, or null if the
        /// manifest is missing/unreadable or has no entry for it.
        /// Triggers the (one-time, cached) manifest load on first call, from any thread.
        /// </summary>
        internal static string? TryGetDebugId(Assembly assembly) =>
            TryGetDebugId(assembly, _manifestOverrideForTests ?? _manifest.Value);

        /// <summary>
        /// Test-only seam: makes the single-argument TryGetDebugId (and therefore
        /// DdRumErrorTracking.BuildSdkFrames) use a caller-supplied manifest instead of the
        /// real app-package one, which needs a real MAUI app package and isn't available in a
        /// desktop unit-test host. Pass null to go back to the real (app-package) manifest.
        /// </summary>
        internal static void SetManifestOverrideForTests(IReadOnlyDictionary<string, string>? manifest) =>
            _manifestOverrideForTests = manifest;

        /// <summary>
        /// Same lookup, against a caller-supplied manifest instead of the cached app-package
        /// one — lets tests exercise the lookup logic (unknown assembly, empty manifest, etc.)
        /// without going through FileSystem.OpenAppPackageFileAsync, which needs a real MAUI
        /// app package and isn't available in a plain unit-test host.
        /// </summary>
        internal static string? TryGetDebugId(Assembly assembly, IReadOnlyDictionary<string, string> manifest)
        {
            var simpleName = assembly.GetName().Name;
            if (simpleName == null)
            {
                return null;
            }

            return manifest.TryGetValue(simpleName, out var debugId) ? debugId : null;
        }

        private static IReadOnlyDictionary<string, string> LoadManifest()
        {
            try
            {
                using var stream = FileSystem.OpenAppPackageFileAsync(ManifestFileName).Result;
                return ParseManifest(stream);
            }
            catch (Exception ex)
            {
                // .Result wraps the real failure in an AggregateException — unwrap it so the
                // log line names the actual cause (e.g. file-not-found) instead of just
                // "One or more errors occurred."
                InternalLog.Log(
                    $"AssemblyDebugId: Failed to load {ManifestFileName}: {ex.GetBaseException().Message}",
                    SdkVerbosity.DEBUG);
                return new Dictionary<string, string>();
            }
        }

        /// <summary>
        /// Parses the manifest JSON, isolated from FileSystem.OpenAppPackageFileAsync so tests
        /// can feed it real (or malformed) JSON directly without a MAUI app package.
        /// </summary>
        internal static IReadOnlyDictionary<string, string> ParseManifest(Stream stream)
        {
            var manifest = JsonSerializer.Deserialize<Dictionary<string, string>>(stream);
            return manifest ?? new Dictionary<string, string>();
        }
    }
}
